// common/edm/EDM.hpp
#pragma once
#include "common/edm/RecoHit.hpp"
#include "common/edm/RawHit.hpp"
#include "common/edm/RawData.hpp"
#include "common/edm/Track.hpp"
#include "common/edm/SimpleFittedTrack.hpp"
#include "common/edm/SimHit.hpp"
#include "common/edm/SimData.hpp"
#include "common/edm/EventSummary.hpp"
#include "common/edm/RmNoiseSummary.hpp"
#include "common/edm/LHCData.hpp"
#include "common/edm/LumiRecord.hpp"