run:
  input: /eos/project/f/faser-upgrade/AHCAL/UJ12_Test/Faser-Physics-021659-000000.root
  MC: false
  log_file: /afs/cern.ch/user/y/ymaruya/private/FASERlink/AHCAL/FAIR/out/run21691^5/log
  output: /afs/cern.ch/user/y/ymaruya/private/FASERlink/AHCAL/FAIR/out/run21691^5/out.root
  nEvents: -1
  log_level: DEBUG
  runNumber: 21659
  poolIndex: 0
reader: 
  type: BinaryRawHitReader
  cfg:
    out_rawhits_key: RawHits
    out_tlu_key: TLURawData
  # type: RootRawHitReader
  # cfg:
  #   out_rawhits_key: RawHits
  #   out_tlu_key: TLURawData
  # type: RootInput
  # cfg:
  #   inputlist: 
  #     - [vector<AHCALRawHit>, RawHits]
  #     - [AHCALTLURawData, TLURawData]
  #     - [vector<AHCALRecoHit>, RecoHits]
  #     - [SimpleFittedTrack, FittedTrack]
  #     - [Track, MuonKFTrack]

algs: # Define the sequence of algorithms to be executed. The order matters.
  # - type: PedestalAlg
  #   cfg:
  #     in_rawhit_key: RawHits
  #     pedestal_to_file: true
  #     pedestal_to_DB: false
  #     out_pedestal_filename: out/run21659/ped.root
  #     use_hittag: false
  #     select_hittag: 0
  - type: AdcToEnergyReadTTreeAlg
    cfg:
      in_rawhit_key: RawHits
      out_recohit_key: RecoHits
      mip:
        file: /afs/cern.ch/user/y/ymaruya/private/FASERlink/AHCAL/FAIR/calibration/reffiles/mip.root
        cut: (gaus_sigma>20)
        cellid_version: 0
      pedestal:
        file: /afs/cern.ch/user/y/ymaruya/private/FASERlink/AHCAL/FAIR/calibration/pedestal_calib/run21722/pedestal.root
        cut: (1)
        cellid_version: 1
      dac:
        file: /afs/cern.ch/user/y/ymaruya/private/FASERlink/AHCAL/FAIR/calibration/reffiles/dac.root
        cut: (1)
        cellid_version: 0
  - type: RmIsolatedHitAlg
    cfg:
      in_recohit_key: RecoHits
      out_recohit_key: RmIsolatedHits
      useNmipWindow: false
      xy_cone: 42.0
      maxMissingLayers: 0
  - type: TrackFitAlg
    cfg:
      in_recohit_key: RmIsolatedHits
      out_track_key: FittedTrack
      use_mip_window: true
      nmipMin: 0.5
      nmipMax: 3.0
      threshold_xy: 20.0
  # - type: MuonKFAlg
  #   cfg:
  #     in_recohit_key: RmIsolatedHits
  #     out_track_key: MuonKFTrack
  #     lastNLayers: 40
  #     minUsedLayers: 10
  #     maxConsecutiveSkips: 5
  #     useNmipWindow: true
  #     nmipMin: 0.2
  #     nmipMax: 3.0
  #     measSigmaXY_mm: 0.0
  #     sigmaTheta: 0.003 
  #     gateD2: 9.0
  #     seedLayerGap: 2
  #     maxSeedHitsPerLayer: 10
  #     skipLayers: [0,2,14,24]
  # - type: MIPAlg
  #   cfg:
  #     in_rawhit_key: RawHits
  #     in_track_key: FittedTrack
  #     string_track_struct: SimpleFittedTrack
  #     track_selection_string: (valid>0)
  #     mip_to_file: true
  #     mip_to_DB: false
  #     out_mip_filename: /afs/cern.ch/user/y/ymaruya/private/FASERlink/AHCAL/FAIR/out/run21691^5/mip.root
  - type: MuonEffAlg
    cfg:
      in_hit_key: RawHits
      in_track_key: FittedTrack
      string_track_struct: SimpleFittedTrack
      track_selection_string: (valid>0)*(chi2xperndf<5)*(chi2xperndf>0)*(chi2yperndf<5)*(chi2yperndf>0)*(nInTrackHits>8)
      out_filename: /afs/cern.ch/user/y/ymaruya/private/FASERlink/AHCAL/FAIR/out/run21691^5/eff.root
      write_to_png: true
      out_png_dir: /afs/cern.ch/user/y/ymaruya/private/FASERlink/AHCAL/FAIR/out/run21691^5/png/
      hittag_or_MIP_cut: true
      xy_size_threshold: 17.0
  - type: RootWriterAlg
    cfg: 
      outputlist:
        - vector<AHCALRecoHit>
        - SimpleFittedTrack
        # - Track