run:
  input: ${FAIR_DATA}/0###run-number###/FaserAHCAL-Physics-0###run-number###-0*.raw
  MC: false
  log_file: ${FAIR_OUT}/###run-number###/log_tmp
  output: ${FAIR_ROOT_OUT}/###run-number###_LHCData.root
  nEvents: -1
  log_level: INFO
  runNumber: ###run-number###
  poolIndex: 0
reader:
  type: BinaryRawHitReader
  cfg:
    out_rawhits_key: RawHits
    out_tlu_key: TLURawData
algs:
  - type: ContextPutter
    cfg: 
      out_RunConfig_key: RunConfig
      out_ConditionStore_key: ConditionStore
  - type: LHCDataReaderAlg
    cfg:
      in_rawdata_key: TLURawData
      out_lhcdata_key: LHCData
      verbose: true
  - type: LumiRecordReaderAlg
    cfg:
      in_rawdata_key: TLURawData
      out_lumirecord_key: LumiRecord
      lumi_tag: OflLumiAcct-Run3-008
      verbose: true
  - type: RootWriterAlg
    cfg: 
      outputlist:
        - RunConfig
        - ConditionStore
        - LHCData
        - AHCALTLURawData
        - LumiRecord
