run:
  input: /eos/experiment/faser/raw/2026/0###run-number###/FaserAHCAL-Physics-0###run-number###-0*.raw
  MC: false
  log_file: /afs/cern.ch/user/y/ymaruya/private/FASERlink/AHCAL/FAIR/out/###run-number###/log_tmp
  output: /eos/project/f/faser-upgrade/AHCAL/FAIR/###run-number###_LHCData.root
  nEvents: -1
  log_level: INFO
  runNumber: ###run-number###
  poolIndex: 0
reader:
  type: BinaryRawHitReader
  cfg:
    out_rawhits_key: RawHits
    out_tlu_key: TLURawData
algs:
  - type: LHCDataReaderAlg
    cfg:
      in_rawdata_key: TLURawData
      out_lhcdata_key: LHCData
      verbose: true
  - type: RootWriterAlg
    cfg: 
      outputlist:
        - LHCData
        - AHCALTLURawData